GET http://localhost:8085/online/1
Accept: application/json

###

GET http://localhost:8085/online
Accept: application/json

###

GET http://localhost:8000/offline
Content-Type: application/json

{}

###

GET http://localhost:8000/offline
Accept: application/json

###


GET http://localhost:8080/sample
Accept: application/json

###