GET http://localhost:8080/online/product
Accept: application/json

###

GET http://localhost:8080/online/employee
Accept: application/json

###

POST http://localhost:8080/online/employee
Content-Type: application/json

{
  "email": "dlalstj5213@irkudos.co.kr",
  "name": "이민민",
  "sex": "여"
}

###