server:
  port: 8085
spring:
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
  cache:
    type: redis
  session:
    store-type: redis # Session store type.
  application:
    name: online-store
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/h2/test-db  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: 1234  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 유레카 클라이언트가 서비스를 등록할 서버 주소를 지정하기 위해 사용함
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    region: ko-KR
    disable-delta: true
  instance:
    # 유레카에 등록되는 ID 값
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
    # 유레카 등록 시 host name 대신 ip 주소 사용
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus
  endpoint:
    shutdown:
      enabled: true