server:
  port: 8081
  servlet:
    context-path: /pinata1
spring:
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    #    driver-class-name: org  # Database를 H2로 사용하겠다.
    url: jdbc:postgresql://localhost:8098/postgres  # H2 접속 정보
    username: postgres  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: 1234  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#  jpa:
#    defer-datasource-initialization: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: create-drop
#  sql:
#    init:
#      mode: never
#
### log4jdbc, Mybatis Console Log
#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: TRACE
#    jdbc:
#      audit: OFF
#      resultset: OFF
#      resultsettable: TRACE   # SQL 결과 데이터 Table을 로그로 남긴다.
#      sqlonly: OFF            # SQL만 로그로 남긴다.
#      sqltiming: TRACE        # SQL과 소요시간을 표기한다.
#      connection: OFF         # 커넥션 확인가능
#    javax:
#      sql:
#        DataSource: OFF
#    org:
#      org:
#        springframework:
#          web: OFF
#      hibernate:
#        SQL: OFF
#        type:
#          descriptor:
#            sql: TRACE
#              BasicBinder: TRACE
#  jpa:
#    show-sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        sql: DEBUG
#        format_seq: DEBUG