server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

sensitiveHeaders: Authorization, Set-Cookie

spring:
  application:
    name: gateway-service
  data:
    redis:
      port: 6379
      host: localhost
      client-type: lettuce
  session:
    store-type: redis
    redis:
      configure-action: none
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter #Global Filter로 지정된 java 파일 이름
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: online-store
          uri: lb://ONLINE-STORE
          predicates:
            - Path=/online/**
          filters:
        - id: offline-store
          uri: lb://OFFLINE-STORE
          predicates:
            - Path=/offline/**
          filters:
            - GatewayAuthorizationSessionFilter
logging:
  level:
    org:
      springframework:
        security: DEBUG